version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  zipkin:
    image: 'openzipkin/zipkin:latest'
    ports:
      - "9411:9411"
