spring:
  datasource:
    url: jdbc:postgresql://monorail.proxy.rlwy.net:33137/railway
    username: postgres
    password: sVvsXuCywNWOKvlEVdujhFldvqGhkARz
  sql:
    init:
      mode: always
  application:
    name: book-service

logging:
  level:
    org.springframework.jdbc: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: when_authorized
