spring:
  datasource:
    url: jdbc:postgresql://localhost/postgres
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
  docker:
    compose:
      lifecycle-management: start_only

logging:
  level:
    org.springframework.jdbc: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: when_authorized
