spring:
  datasource:
    url: jdbc:postgresql://viaduct.proxy.rlwy.net:26036/railway
    username: postgres
    password: ALPrrgVGEUxRzNlsInxDuGtfFxqadubx
  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.jdbc: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: when_authorized
